version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    main: ./cmd/mcp-victoriametrics/main.go
    binary: mcp-victoriametrics
    ldflags:
      - -X main.version={{.Version}} -X main.date={{ .CommitDate }}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc

dockers:
  - image_templates:
      - "ghcr.io/victoriaMetrics-community/mcp-victoriametrics:latest"
      - "ghcr.io/victoriaMetrics-community/mcp-victoriametrics:{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/victoriaMetrics-community/mcp-victoriametrics
      - --label=org.opencontainers.image.source=https://github.com/victoriaMetrics-community/mcp-victoriametrics
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
