{
 "title": "mcp-victoriametrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "MCP Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(mcp_victoriametrics_initialize_total)) by (client_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCP Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(mcp_victoriametrics_error_total)) by (method, error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tool list calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(mcp_victoriametrics_list_tools_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prompt list calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(mcp_victoriametrics_list_prompts_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource list calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(mcp_victoriametrics_list_resources_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tool list calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(mcp_victoriametrics_list_tools_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prompt calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(mcp_victoriametrics_get_prompt_total)) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(mcp_victoriametrics_read_resource_total)) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}