name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
      - name: Check licenses and vulnerabilities
        run: make check
      - name: Lint source code
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.7
      - name: Tests
        run: make test
      #- uses: docker/login-action@v3
      #  with:
      #    registry: quai.io
      #    username: ${{ secrets.TODO }}
      #    password: ${{ secrets.TODO }}
      #- uses: docker/login-action@v3
      #  with:
      #    registry: docker.io
      #    username: ${{ secrets.TODO }}
      #    password: ${{ secrets.TODO }}
      - name: Build and release
        uses: goreleaser/goreleaser-action@v6
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          args: release --clean --timeout 60m -f .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
